### ISSUE TITLE
unmet dependency on git-lfs

### ISSUE THREAD

**Issue by jim-perkins** [CaseyBakey/chaosp#10]
https://github.com/CaseyBakey/chaosp/blob/abf695ff0e87aa955a16873745638e4303d090c4/build.sh#L603

sudo apt install git-lfs

**Comment by CaseyBakey** [comment]
Yes, my bad.

I'll add it to my next Android 11 update!

**Comment by CaseyBakey** [comment]
I'm closing this since it's fixed on branch 11.
