### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Ashaman-** [CaseyBakey/chaosp#12]
`install-build-deps-android.sh complete.
2020-12-17 09:30:26: Running gclient sync (this takes a while)
use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)                                                                                                                
use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)  
Syncing projects: 100% (383/383), done.                                                         
Running hooks: 100% (93/93), done.                                      
Done. Made 34567 targets from 2136 files in 23117ms
2020-12-17 09:31:48: Building chromium chrome_modern_public_apk target
ninja: Entering directory `out/Default/'
[1334/1334] STAMP obj/chrome/android/chrome_modern_public_apk.stamp
2020-12-17 09:36:09: Building chromium system_webview_apk target
ninja: Entering directory `out/Default/'
[1149/1149] STAMP obj/android_webview/system_webview_apk.stamp
cp: cannot create regular file '/home/user/chaosp/rattlesnake-os/external/chromium-webview/prebuilt/arm64/webview.apk': No such file or directory`

Is there a way to build Android 9? I downloaded the sources for 9.0.0_r59, but I think the script updated everything to the latest versions before running the build.
Only changes I made to build.sh were setting ADD_MAGISK and ADD_OPENGAPPS both to true.

**Comment by CaseyBakey** [comment]
Hello.

The error you got is the same as [this](https://github.com/CaseyBakey/chaosp/issues/9).

I'm actually working on Android 11 and got it running on Pixel 3/3a/4a.

If your device supports Android 11, you'll be able to take a look when I'll release my next update!

**Comment by CaseyBakey** [comment]
Closing this as it's fixed on master.
