### ISSUE TITLE
Can not build Android 11 at all - process "dies" after chromium with errors about "external" folder missing 

### ISSUE THREAD

**Issue by AlexandraKey** [CaseyBakey/chaosp#17]
Hello!
Basically what it says on the tin can.

I have a separate PC dedicated to this. Followed all instruction.

Full log available:
[FullLog.txt](https://github.com/CaseyBakey/chaosp/files/7740645/FullLog.txt)

The main symptom seems to be:

ls: cannot access '/home/user1/chaosp/aosp/external/chromium/patches': No such file or directory

2021-12-19 13:03:18: trichrome_certdigest=6516ec514b07e7921c6ea0892c3d4f12a40ad16afa81af21bc8dd25a92459ec0

cp: cannot stat '/home/user1/chaosp/aosp/external/chromium/args.gn': No such file or directory

And then it just...dies. @CaseyBakey / @corrmaan please help :-)

**Comment by CaseyBakey** [comment]
To build AOSP, I think that downloading AOSP is a must.

As you can see, your chaosp/aosp folder should be quite empty.

Look for "Running aosp_repo_sync" step in your log...

It's linked to a breaking change in RattlesnakeOS, which is a project CHAOSP uses.

Here some more details: https://www.reddit.com/r/RattlesnakeOS/comments/qt85y3/release_20211112_breaking_apv_changes_and_pixel/

Look for the given new env variables: apv-remote, apv-branch and apv-revision

Look for my last commit in 12.0-dev branch which fixes this error.

Bonito supports Android 12 and thus, you should switch to the 12.0-dev branch.

I won't support 11.0 anymore, but feel free to P/R your fix on 11.0 if you do it.


Regards,
