### ISSUE TITLE
Project direction, other options

### ISSUE THREAD

**Issue by ypid** [CaseyBakey/chaosp#3]
Hi @CaseyBakey,

Sadly, I only found your project just now. I was also on that path (building Rattlesnake OS locally after Copperhead OS disappeared). But in the mean time I found https://github.com/hashbang/aosp-build which I since contribute to. I assess it as a much more stable and better designed build system – in short more in line with my goals for such a build system. Do you know it?

I reviewed the current state of CHAOSP, unsurprising, it has big overlap to Rattlesnake that I once dissected similarly but without making it a proper/automated local build script.

I like the extra options and TODOs you have. That is something that is not the focus of Hashbang OS but it could be a opt-in.

Maybe we can combine forces somehow?

**Comment by CaseyBakey** [comment]
Hi there,

I'm actually trying to "port" this project to Android 10, for my personal use/daily driver.

Once done, I indeed will take a look at hashbang since it looked promising when I (over)looked it few months ago.
