### ISSUE TITLE
Unable to get latest AOSP build information 

### ISSUE THREAD

**Issue by osunde** [CaseyBakey/chaosp#7]
./build.sh blueline

ERROR: Unable to get latest AOSP build information. Stopping build. This lookup is pretty fragile and can break on any page redesign of https://developers.google.com/android/images

**Comment by CaseyBakey** [comment]
I'm sorry, I didn't notice your issue but I did encounter it myself.
We're not affected by it anymore since I rebased the script on latest RattlesnakeOS script, and it did change the way this information is recovered.
