### ISSUE TITLE
script errored out because there was no chromium directory

### ISSUE THREAD

**Issue by jim-perkins** [CaseyBakey/chaosp#8]
https://github.com/CaseyBakey/chaosp/blob/abf695ff0e87aa955a16873745638e4303d090c4/build.sh#L236

I created the directory , restarted script and it is progressing

**Comment by CaseyBakey** [comment]
My bad, a dry-run would have catched this!

**Comment by CaseyBakey** [comment]
I'm closing this since it's fixed on branch 11.
