### ISSUE TITLE
Tried to write to a directory that didnt exist

### ISSUE THREAD

**Issue by jim-perkins** [CaseyBakey/chaosp#9]
https://github.com/CaseyBakey/chaosp/blob/abf695ff0e87aa955a16873745638e4303d090c4/build.sh#L539

**Comment by CaseyBakey** [comment]
Yes, I should have catched this doing a dry-run, but I didn't since lazy/too long to rebuild all...

It's just a missing mkdir for the webview :/

I keep it open to don't forget to check for in my next Android 11 update!

**Comment by CaseyBakey** [comment]
Closing this because it's fixed on branch 11.
